var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",da=(a,b)=>{throw b;},h="";"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src);h=0!==h.indexOf("blob:")?h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var ea=f.print||console.log.bind(console),l=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);
f.quit&&(da=f.quit);var m;f.wasmBinary&&(m=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&fa("no native wasm support detected");var ha,p=!1,ia,ja,q,ka,r,u,v,la,ma=[],na=[],oa=[],pa=[],qa=[];function ra(){var a=f.preRun.shift();ma.unshift(a)}var w=0,sa=null,ta=null;function fa(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";l(a);p=!0;ia=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function ua(a){return a.startsWith("data:application/octet-stream;base64,")}var x;x="index.wasm";if(!ua(x)){var va=x;x=f.locateFile?f.locateFile(va,h):h+va}function wa(a){if(a==x&&m)return new Uint8Array(m);throw"both async and sync fetching of the wasm failed";}function xa(a){return m||"function"!=typeof fetch?Promise.resolve().then(()=>wa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>wa(a))}
function ya(a,b,c){return xa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{l(`failed to asynchronously prepare wasm: ${d}`);fa(d)})}function za(a,b){var c=x;m||"function"!=typeof WebAssembly.instantiateStreaming||ua(c)||"function"!=typeof fetch?ya(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l(`wasm streaming compile failed: ${e}`);l("falling back to ArrayBuffer instantiation");return ya(c,a,b)}))}
function Aa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Ba=a=>{for(;0<a.length;)a.shift()(f)},Ca=0;function Da(){for(var a=y.length-1;0<=a;--a)Ea(a);y=[];Fa=[]}var Fa=[];function Ga(){if(navigator.userActivation?navigator.userActivation.isActive:Ca&&Ha.Bd)for(var a=0;a<Fa.length;++a){var b=Fa[a];Fa.splice(a,1);--a;b.Md.apply(null,b.Dd)}}var y=[];function Ea(a){var b=y[a];b.target.removeEventListener(b.Oc,b.td,b.ld);y.splice(a,1)}
function Ia(a){function b(d){++Ca;Ha=a;Ga();a.ud(d);Ga();--Ca}if(!a.target)return-4;if(a.qd)a.td=b,a.target.addEventListener(a.Oc,b,a.ld),y.push(a),Ja||(pa.push(Da),Ja=!0);else for(var c=0;c<y.length;++c)y[c].target==a.target&&y[c].Oc==a.Oc&&Ea(c--);return 0}
var Ja,Ha,Ka,La="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,z=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&La)return La.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ma=[0,document,window],Na=a=>{a=2<a?a?z(q,a):"":a;return Ma[a]||document.querySelector(a)},B=(a,b,c)=>{var d=q;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var n=a.charCodeAt(++g);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(b>=c)break;d[b++]=k}else{if(2047>=k){if(b+1>=c)break;d[b++]=192|k>>6}else{if(65535>=k){if(b+2>=c)break;d[b++]=224|k>>12}else{if(b+3>=c)break;d[b++]=240|k>>18;d[b++]=128|k>>12&63}d[b++]=128|k>>6&63}d[b++]=128|k&63}}d[b]=
0;return b-e},Oa=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,k)=>b.drawElementsInstancedANGLE(c,d,e,g,k))},Pa=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>
b.isVertexArrayOES(c))},Qa=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Ra=1,Sa=[],C=[],Ta=[],D=[],E=[],F=[],Ua=[],Va=[],G=[],Wa={},Xa=4;function H(a){Ya||(Ya=a)}
var Za=a=>{for(var b=Ra++,c=a.length;c<b;c++)a[c]=null;return b},ab=(a,b)=>{a.Mc||(a.Mc=a.getContext,a.getContext=function(d,e){e=a.Mc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?$a(c,b):0},$a=(a,b)=>{var c=Za(Va),d={handle:c,attributes:b,version:b.xd,Wc:a};a.canvas&&(a.canvas.Ad=d);Va[c]=d;("undefined"==typeof b.sd||b.sd)&&bb(d);return c},bb=a=>{a||(a=cb);if(!a.wd){a.wd=!0;var b=a.Wc;Oa(b);Pa(b);Qa(b);b.Jc=b.getExtension("EXT_disjoint_timer_query");
b.Ld=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},db={},Ya,cb,eb=[],fb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=I[c](),k=g&&Za(d);g?(g.name=k,d[k]=g):H(1282);r[b+4*e>>2]=k}},gb=(a,b,c,d,e,g,k,n)=>{b=C[b];if(a=I[a](b,c))d=n&&B(a.name,n,d),e&&(r[e>>2]=d),g&&(r[g>>2]=a.size),k&&(r[k>>2]=a.type)},hb=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&H(1280);return;case 36345:d=
0;break;case 34466:var e=I.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=I.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":H(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:H(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+
4*a>>2]=e[a];break;case 2:v[b+4*a>>2]=e[a];break;case 4:ja[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){H(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:H(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=d;u[b>>2]=c;u[b+4>>2]=(c-u[b>>2])/4294967296;break;case 0:r[b>>2]=d;break;case 2:v[b>>2]=d;break;case 4:ja[b>>
0]=d?1:0}}else H(1281)},ib=(a,b,c)=>{if(c){a=I.Jc.getQueryObjectEXT(G[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d;u[c+4>>2]=(d-u[c>>2])/4294967296}else H(1281)},jb=(a,b,c)=>{if(c){a=I.Jc.getQueryObjectEXT(G[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;r[c>>2]=d}else H(1281)},kb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},mb=a=>{var b=kb(a)+1,c=lb(b);c&&B(a,c,b);return c},nb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),
ob=a=>{var b=a.Lc,c=a.kd,d;if(!b)for(a.Lc=b={},a.jd={},d=0;d<I.getProgramParameter(a,35718);++d){var e=I.getActiveUniform(a,d);var g=e.name;e=e.size;var k=nb(g);k=0<k?g.slice(0,k):g;var n=a.$c;a.$c+=e;c[k]=[e,n];for(g=0;g<e;++g)b[n]=g,a.jd[n++]=k}},J=a=>{var b=I.rd;if(b){var c=b.Lc[a];"number"==typeof c&&(b.Lc[a]=c=I.getUniformLocation(b,b.jd[a]+(0<c?"["+c+"]":"")));return c}H(1282)},pb=(a,b,c,d)=>{if(c)if(a=C[a],ob(a),a=I.getUniform(a,J(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>
2]=a;break;case 2:v[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b]}else H(1281)},qb=(a,b,c,d)=>{if(c)if(a=I.getVertexAttrib(a,b),34975==b)r[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:v[c>>2]=a;break;case 5:r[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b];break;case 5:r[c+4*b>>2]=Math.fround(a[b])}else H(1281)},rb=(a,b,c,
d,e)=>{a-=5120;a=1==a?q:4==a?r:6==a?v:5==a||28922==a?u:ka;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),k=Xa;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+k-1&-k)>>g)},K=[],sb=[],tb=a=>{a instanceof Aa||"unwind"==a||da(1,a)},ub=a=>{ia=a;if(!noExitRuntime){if(f.onExit)f.onExit(a);p=!0}da(a,new Aa(a))},vb=a=>{ia=a;ub(a)},wb=!1,L=null,M=0,xb=null,yb=0,zb=0,Ab=0,N=0,Bb=[],Cb={},Db,Eb,Fb,Gb=!1,Hb=!1,Ib=[];
function Jb(){function a(){Hb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!Kb){Kb=!0;var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!Hb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Lb(a,b,c,d){if(b&&f.Kc&&a==f.canvas)return f.Kc;var e;if(b){var g={antialias:!1,alpha:!1,xd:1};if(d)for(var k in d)g[k]=d[k];if("undefined"!=typeof db&&(e=ab(a,g)))var n=Va[e].Wc}else n=a.getContext("2d");if(!n)return null;c&&(b||"undefined"==typeof I||fa("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Kc=n,b&&(cb=Va[e],f.Kc=I=cb&&cb.Wc),f.Nd=b,Ib.forEach(t=>t()),Jb());return n}var Mb=!1,Nb=void 0,O=void 0;
function Ob(a,b){function c(){Gb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Pb,Nb&&d.requestPointerLock(),Gb=!0,O?("undefined"!=typeof SDL&&(r[SDL.screen>>2]=u[SDL.screen>>2]|8388608),Qb(f.canvas),Rb()):Qb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),O?("undefined"!=typeof SDL&&(r[SDL.screen>>2]=u[SDL.screen>>2]&-8388609),
Qb(f.canvas),Rb()):Qb(d));if(f.onFullScreen)f.onFullScreen(Gb);if(f.onFullscreen)f.onFullscreen(Gb)}Nb=a;O=b;"undefined"==typeof Nb&&(Nb=!0);"undefined"==typeof O&&(O=!1);var d=f.canvas;Mb||(Mb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}function Pb(){if(!Gb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Sb=0;
function Tb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Sb)Sb=b+1E3/60;else for(;b+2>=Sb;)Sb+=1E3/60;setTimeout(a,Math.max(Sb-b,0))}}var P=0,Q=0,Ub=0,Vb=0;
function Wb(a){if(Hb)"mousemove"!=a.type&&"mozMovementX"in a?Ub=Vb=0:(Ub=a.movementX||a.mozMovementX||a.webkitMovementX||0,Vb=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(P=SDL.Jd+Ub,Q=SDL.Kd+Vb):(P+=Ub,Q+=Vb);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==a.type&&
"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,Ub=e-P,Vb=a-Q,P=e,Q=a)}}var Xb=[];function Rb(){var a=f.canvas;Xb.forEach(b=>b(a.width,a.height))}function Yb(a,b,c){Qb(f.canvas,a,b);c||Rb()}
function Qb(a,b,c){b&&c?(a.zd=b,a.vd=c):(b=a.zd,c=a.vd);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}O?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Kb,$b=(a,b)=>{zb=a;Ab=b;if(xb)if(wb||(wb=!0),0==a)L=function(){var d=Math.max(0,Eb+b-Zb())|0;setTimeout(Fb,d)};else if(1==a)L=function(){Tb(Fb)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}L=function(){setImmediate(Fb)}}},Zb;Zb=()=>performance.now();
var ac=(a,b,c,d,e)=>{!xb||fa("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");xb=a;yb=d;var g=M;wb=!1;Fb=function(){if(!p)if(0<Bb.length){var k=Bb.shift();k.Id(k.Cd);if(Db){var n=Db,t=0==n%1?n-1:Math.floor(n);Db=k.Gd?t:(8*n+(t+.5))/9}f.setStatus&&(k=f.statusMessage||"Please wait...",n=Db,t=Cb.Hd,n?n<t?f.setStatus(k+" ("+(t-n)+"/"+t+")"):f.setStatus(k):f.setStatus(""));
g<M||setTimeout(Fb,0)}else if(!(g<M))if(N=N+1|0,1==zb&&1<Ab&&0!=N%Ab)L();else{0==zb&&(Eb=Zb());if(!(p||f.preMainLoop&&!1===f.preMainLoop())){if(!p)try{if(a(),!noExitRuntime)try{ia=k=ia,ub(k)}catch(A){tb(A)}}catch(A){tb(A)}f.postMainLoop&&f.postMainLoop()}g<M||("object"==typeof SDL&&SDL.audio&&SDL.audio.yd&&SDL.audio.yd(),L())}};e||(b&&0<b?$b(0,1E3/b):$b(1,1),L());if(c)throw"unwind";},bc=[],cc,R=a=>{var b=bc[a];b||(a>=bc.length&&(bc.length=a+1),bc[a]=b=cc.get(a));return b},dc=(a,b,c,d)=>{Ka||(Ka=lb(36));
a=Na(a);return Ia({target:a,Oc:"resize",qd:d,ud:(e=event)=>{if(e.target==a){var g=document.body;if(g){var k=Ka;r[k>>2]=e.detail;r[k+4>>2]=g.clientWidth;r[k+8>>2]=g.clientHeight;r[k+12>>2]=innerWidth;r[k+16>>2]=innerHeight;r[k+20>>2]=outerWidth;r[k+24>>2]=outerHeight;r[k+28>>2]=pageXOffset;r[k+32>>2]=pageYOffset;R(d)(10,k,b)&&e.preventDefault()}}},ld:c})},ec=[null,[],[]];
function fc(a,b,c,d){this.id=a;this.y=this.x=0;this.Zc=!1;this.hd=this.gd=0;this.width=b;this.height=c;this.fd=b;this.ed=c;this.title=d;this.attributes=S;this.dd={208897:212993,208898:0,208899:0};this.buttons=0;this.keys=[];this.Yc=[];this.ad=this.Pc=this.bd=this.Uc=this.Nc=this.Xc=this.Tc=this.nd=this.cd=this.md=this.Vc=this.title=null}
for(var T=null,gc=null,U=null,hc=null,S=null,ic={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},jc=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;
case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;
case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;
case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;
case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}},kc=()=>{var a=
T,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b},lc=a=>{T&&T.ad&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||R(T.ad)(T.id,a))},mc=(a,b)=>{if(T){var c=jc(a);if(-1!=c){var d=b&&T.keys[c];T.keys[c]=b;T.Yc[a]=b;T.Pc&&(d&&(b=2),R(T.Pc)(T.id,c,a,b,kc()))}}},oc=()=>{nc()},pc=()=>{nc()},qc=a=>{mc(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()},rc=a=>{mc(a.keyCode,0)},sc=()=>{if(T)for(var a=0;a<T.Yc.length;++a)T.Yc[a]&&mc(a,0)},tc=
a=>{T&&(Wb(a),a.target==f.canvas&&T.Xc&&T.Xc&&R(T.Xc)(T.id,P,Q))},uc=a=>{T&&a.target==f.canvas&&T.Nc&&R(T.Nc)(T.id,1)},vc=a=>{T&&a.target==f.canvas&&T.Nc&&R(T.Nc)(T.id,0)},wc=(a,b)=>{if(T&&(Wb(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){T.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else T.buttons&=~(1<<c);T.Tc&&R(T.Tc)(T.id,c,b,kc())}},xc=a=>{T&&wc(a,1)},V=a=>{T&&wc(a,0)},yc=a=>{switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/
120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(T&&T.Uc&&a.target==f.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;R(T.Uc)(T.id,b,c);a.preventDefault()}},W={},zc=[],Ac=null,nc=()=>{if(N!==Ac||!N){zc=navigator.getGamepads?navigator.getGamepads():
navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];Ac=N;for(var a=0;a<zc.length;++a){var b=zc[a];if(b){W[a]||(ea("glfw joystick connected:",a),W[a]={id:mb(b.id),Fd:b.buttons.length,Ed:b.axes.length,buttons:lb(b.buttons.length),axes:lb(4*b.axes.length)});for(var c=W[a],d=0;d<b.buttons.length;++d)ja[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)v[c.axes+4*d>>2]=b.axes[d]}else W[a]&&(ea("glfw joystick disconnected",a),Bc(W[a].id),Bc(W[a].buttons),Bc(W[a].axes),delete W[a])}}},
Cc=a=>{if(T&&T.bd&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1},Dc=a=>{if(T&&T.bd)return a.preventDefault(),!1},Ec=a=>{!Hb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),a.preventDefault())},I,X=0;32>X;++X)eb.push(Array(X));var Fc=new Float32Array(288);for(X=0;288>X;++X)K[X]=Fc.subarray(0,X+1);var Gc=new Int32Array(288);for(X=0;288>X;++X)sb[X]=Gc.subarray(0,X+1);f.requestFullscreen=(a,b)=>Ob(a,b);f.requestAnimationFrame=a=>Tb(a);
f.setCanvasSize=(a,b,c)=>Yb(a,b,c);f.pauseMainLoop=()=>{L=null;M++};f.resumeMainLoop=()=>{M++;var a=zb,b=Ab,c=xb;xb=null;ac(c,0,!1,yb,!0);$b(a,b);L()};f.getUserMedia=()=>{window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=(a,b,c,d)=>Lb(a,b,c,d);
var Hc={B:(a,b,c)=>{a=Na(a);if(!a)return-4;a=0>Ma.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};la[b>>3]=a.width;la[c>>3]=a.height;return 0},Ja:a=>{if(a){var b=document.pointerLockElement||document.Mc||document.pd||document.od;r[a>>2]=!!b;var c=b&&b.id?b.id:"";B(b?b==window?"#window":b==screen?"#screen":b&&b.nodeName?b.nodeName:"":"",a+4,128);B(c,a+132,128)}return document.body&&(document.body.requestPointerLock||document.body.Mc||document.body.pd||document.body.od)?0:-1},ka:function(a){I.activeTexture(a)},
ja:(a,b)=>{I.attachShader(C[a],F[b])},Ba:(a,b)=>{I.Jc.beginQueryEXT(a,G[b])},ia:(a,b,c)=>{I.bindAttribLocation(C[a],b,c?z(q,c):"")},ha:(a,b)=>{I.bindBuffer(a,Sa[b])},ga:(a,b)=>{I.bindFramebuffer(a,Ta[b])},fa:(a,b)=>{I.bindRenderbuffer(a,D[b])},ea:(a,b)=>{I.bindTexture(a,E[b])},ta:a=>{I.bindVertexArray(Ua[a])},da:function(a,b,c,d){I.blendColor(a,b,c,d)},ca:function(a){I.blendEquation(a)},ba:function(a,b){I.blendEquationSeparate(a,b)},aa:function(a,b){I.blendFunc(a,b)},$:function(a,b,c,d){I.blendFuncSeparate(a,
b,c,d)},_:(a,b,c,d)=>{I.bufferData(a,c?q.subarray(c,c+b):b,d)},Z:(a,b,c,d)=>{I.bufferSubData(a,b,q.subarray(d,d+c))},Y:function(a){return I.checkFramebufferStatus(a)},W:function(a){I.clear(a)},V:function(a,b,c,d){I.clearColor(a,b,c,d)},U:function(a){I.clearDepth(a)},T:function(a){I.clearStencil(a)},S:(a,b,c,d)=>{I.colorMask(!!a,!!b,!!c,!!d)},R:a=>{I.compileShader(F[a])},Q:(a,b,c,d,e,g,k,n)=>{I.compressedTexImage2D(a,b,c,d,e,g,n?q.subarray(n,n+k):null)},P:(a,b,c,d,e,g,k,n,t)=>{I.compressedTexSubImage2D(a,
b,c,d,e,g,k,t?q.subarray(t,t+n):null)},O:function(a,b,c,d,e,g,k,n){I.copyTexImage2D(a,b,c,d,e,g,k,n)},N:function(a,b,c,d,e,g,k,n){I.copyTexSubImage2D(a,b,c,d,e,g,k,n)},L:()=>{var a=Za(C),b=I.createProgram();b.name=a;b.Sc=b.Qc=b.Rc=0;b.$c=1;C[a]=b;return a},K:a=>{var b=Za(F);F[b]=I.createShader(a);return b},J:function(a){I.cullFace(a)},I:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Sa[d];e&&(I.deleteBuffer(e),e.name=0,Sa[d]=null)}},H:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+4*c>>2],e=Ta[d];e&&(I.deleteFramebuffer(e),
e.name=0,Ta[d]=null)}},G:a=>{if(a){var b=C[a];b?(I.deleteProgram(b),b.name=0,C[a]=null):H(1281)}},Da:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=G[d];e&&(I.Jc.deleteQueryEXT(e),G[d]=null)}},F:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=D[d];e&&(I.deleteRenderbuffer(e),e.name=0,D[d]=null)}},E:a=>{if(a){var b=F[a];b?(I.deleteShader(b),F[a]=null):H(1281)}},D:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=E[d];e&&(I.deleteTexture(e),e.name=0,E[d]=null)}},sa:(a,b)=>{for(var c=0;c<a;c++){var d=
r[b+4*c>>2];I.deleteVertexArray(Ua[d]);Ua[d]=null}},C:function(a){I.depthFunc(a)},A:a=>{I.depthMask(!!a)},z:function(a,b){I.depthRange(a,b)},y:(a,b)=>{I.detachShader(C[a],F[b])},x:function(a){I.disable(a)},w:a=>{I.disableVertexAttribArray(a)},v:(a,b,c)=>{I.drawArrays(a,b,c)},na:(a,b,c,d)=>{I.drawArraysInstanced(a,b,c,d)},oa:(a,b)=>{for(var c=eb[a],d=0;d<a;d++)c[d]=r[b+4*d>>2];I.drawBuffers(c)},u:(a,b,c,d)=>{I.drawElements(a,b,c,d)},ma:(a,b,c,d,e)=>{I.drawElementsInstanced(a,b,c,d,e)},t:function(a){I.enable(a)},
s:a=>{I.enableVertexAttribArray(a)},Aa:a=>{I.Jc.endQueryEXT(a)},r:function(){I.finish()},q:function(){I.flush()},p:(a,b,c,d)=>{I.framebufferRenderbuffer(a,b,c,D[d])},o:(a,b,c,d,e)=>{I.framebufferTexture2D(a,b,c,E[d],e)},n:function(a){I.frontFace(a)},m:(a,b)=>{fb(a,b,"createBuffer",Sa)},k:(a,b)=>{fb(a,b,"createFramebuffer",Ta)},Ea:(a,b)=>{for(var c=0;c<a;c++){var d=I.Jc.createQueryEXT();if(!d){for(H(1282);c<a;)r[b+4*c++>>2]=0;break}var e=Za(G);d.name=e;G[e]=d;r[b+4*c>>2]=e}},j:(a,b)=>{fb(a,b,"createRenderbuffer",
D)},i:(a,b)=>{fb(a,b,"createTexture",E)},ra:function(a,b){fb(a,b,"createVertexArray",Ua)},l:function(a){I.generateMipmap(a)},h:(a,b,c,d,e,g,k)=>{gb("getActiveAttrib",a,b,c,d,e,g,k)},zc:(a,b,c,d,e,g,k)=>{gb("getActiveUniform",a,b,c,d,e,g,k)},yc:(a,b,c,d)=>{a=I.getAttachedShaders(C[a]);var e=a.length;e>b&&(e=b);r[c>>2]=e;for(b=0;b<e;++b)r[d+4*b>>2]=F.indexOf(a[b])},xc:(a,b)=>I.getAttribLocation(C[a],b?z(q,b):""),wc:(a,b)=>{hb(a,b,4)},vc:(a,b,c)=>{c?r[c>>2]=I.getBufferParameter(a,b):H(1281)},uc:()=>
{var a=I.getError()||Ya;Ya=0;return a},tc:(a,b)=>{hb(a,b,2)},sc:(a,b,c,d)=>{a=I.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r[d>>2]=a},rc:(a,b)=>{hb(a,b,0)},oc:(a,b,c,d)=>{a=I.getProgramInfoLog(C[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,d,b):0;c&&(r[c>>2]=b)},qc:(a,b,c)=>{if(c)if(a>=Ra)H(1281);else if(a=C[a],35716==b)a=I.getProgramInfoLog(a),null===a&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(35719==b){if(!a.Sc)for(b=
0;b<I.getProgramParameter(a,35718);++b)a.Sc=Math.max(a.Sc,I.getActiveUniform(a,b).name.length+1);r[c>>2]=a.Sc}else if(35722==b){if(!a.Qc)for(b=0;b<I.getProgramParameter(a,35721);++b)a.Qc=Math.max(a.Qc,I.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.Qc}else if(35381==b){if(!a.Rc)for(b=0;b<I.getProgramParameter(a,35382);++b)a.Rc=Math.max(a.Rc,I.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.Rc}else r[c>>2]=I.getProgramParameter(a,b);else H(1281)},va:ib,xa:jb,ua:ib,wa:jb,ya:(a,b,c)=>{c?r[c>>2]=I.Jc.getQueryEXT(a,
b):H(1281)},nc:(a,b,c)=>{c?r[c>>2]=I.getRenderbufferParameter(a,b):H(1281)},lc:(a,b,c,d)=>{a=I.getShaderInfoLog(F[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,d,b):0;c&&(r[c>>2]=b)},kc:(a,b,c,d)=>{a=I.getShaderPrecisionFormat(a,b);r[c>>2]=a.rangeMin;r[c+4>>2]=a.rangeMax;r[d>>2]=a.precision},jc:(a,b,c,d)=>{if(a=I.getShaderSource(F[a]))b=0<b&&d?B(a,d,b):0,c&&(r[c>>2]=b)},mc:(a,b,c)=>{c?35716==b?(a=I.getShaderInfoLog(F[a]),null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?(a=I.getShaderSource(F[a]),
r[c>>2]=a?a.length+1:0):r[c>>2]=I.getShaderParameter(F[a],b):H(1281)},ic:a=>{var b=Wa[a];if(!b){switch(a){case 7939:b=I.getSupportedExtensions()||[];b=b.concat(b.map(d=>"GL_"+d));b=mb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=I.getParameter(a))||H(1280);b=b&&mb(b);break;case 7938:b=mb("OpenGL ES 2.0 ("+I.getParameter(7938)+")");break;case 35724:b=I.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+
c[1]+" ("+b+")");b=mb(b);break;default:H(1280)}Wa[a]=b}return b},hc:(a,b,c)=>{c?v[c>>2]=I.getTexParameter(a,b):H(1281)},gc:(a,b,c)=>{c?r[c>>2]=I.getTexParameter(a,b):H(1281)},cc:(a,b)=>{b=b?z(q,b):"";if(a=C[a]){ob(a);var c=a.Lc,d=0,e=b,g=nb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.kd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||I.getUniformLocation(a,b)))return d}else H(1281);return-1},fc:(a,b,c)=>{pb(a,b,c,2)},dc:(a,b,c)=>{pb(a,b,c,0)},$b:(a,b,c)=>{c?r[c>>2]=I.getVertexAttribOffset(a,b):
H(1281)},bc:(a,b,c)=>{qb(a,b,c,2)},ac:(a,b,c)=>{qb(a,b,c,5)},_b:function(a,b){I.hint(a,b)},Zb:a=>(a=Sa[a])?I.isBuffer(a):0,Yb:function(a){return I.isEnabled(a)},Xb:a=>(a=Ta[a])?I.isFramebuffer(a):0,Wb:a=>(a=C[a])?I.isProgram(a):0,Ca:a=>(a=G[a])?I.Jc.isQueryEXT(a):0,Ub:a=>(a=D[a])?I.isRenderbuffer(a):0,Tb:a=>(a=F[a])?I.isShader(a):0,Sb:a=>(a=E[a])?I.isTexture(a):0,pa:a=>(a=Ua[a])?I.isVertexArray(a):0,Rb:function(a){I.lineWidth(a)},Qb:a=>{a=C[a];I.linkProgram(a);a.Lc=0;a.kd={}},Pb:(a,b)=>{3317==a&&
(Xa=b);I.pixelStorei(a,b)},Ob:function(a,b){I.polygonOffset(a,b)},za:(a,b)=>{I.Jc.queryCounterEXT(G[a],b)},Nb:(a,b,c,d,e,g,k)=>{(k=rb(g,e,c,d,k))?I.readPixels(a,b,c,d,e,g,k):H(1280)},Mb:()=>{},Lb:function(a,b,c,d){I.renderbufferStorage(a,b,c,d)},Jb:(a,b)=>{I.sampleCoverage(a,!!b)},Ib:function(a,b,c,d){I.scissor(a,b,c,d)},Hb:()=>{H(1280)},Gb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var k=d?r[d+4*g>>2]:-1,n=r[c+4*g>>2];k=n?z(q,n,0>k?void 0:k):"";e+=k}I.shaderSource(F[a],e)},Fb:function(a,b,c){I.stencilFunc(a,
b,c)},Eb:function(a,b,c,d){I.stencilFuncSeparate(a,b,c,d)},Db:function(a){I.stencilMask(a)},Cb:function(a,b){I.stencilMaskSeparate(a,b)},Bb:function(a,b,c){I.stencilOp(a,b,c)},Ab:function(a,b,c,d){I.stencilOpSeparate(a,b,c,d)},yb:(a,b,c,d,e,g,k,n,t)=>{I.texImage2D(a,b,c,d,e,g,k,n,t?rb(n,k,d,e,t):null)},xb:function(a,b,c){I.texParameterf(a,b,c)},wb:(a,b,c)=>{I.texParameterf(a,b,v[c>>2])},vb:function(a,b,c){I.texParameteri(a,b,c)},ub:(a,b,c)=>{I.texParameteri(a,b,r[c>>2])},tb:(a,b,c,d,e,g,k,n,t)=>{var A=
null;t&&(A=rb(n,k,e,g,t));I.texSubImage2D(a,b,c,d,e,g,k,n,A)},sb:(a,b)=>{I.uniform1f(J(a),b)},rb:(a,b,c)=>{if(288>=b)for(var d=K[b-1],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);I.uniform1fv(J(a),d)},qb:(a,b)=>{I.uniform1i(J(a),b)},pb:(a,b,c)=>{if(288>=b)for(var d=sb[b-1],e=0;e<b;++e)d[e]=r[c+4*e>>2];else d=r.subarray(c>>2,c+4*b>>2);I.uniform1iv(J(a),d)},nb:(a,b,c)=>{I.uniform2f(J(a),b,c)},mb:(a,b,c)=>{if(144>=b)for(var d=K[2*b-1],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+
4)>>2];else d=v.subarray(c>>2,c+8*b>>2);I.uniform2fv(J(a),d)},lb:(a,b,c)=>{I.uniform2i(J(a),b,c)},kb:(a,b,c)=>{if(144>=b)for(var d=sb[2*b-1],e=0;e<2*b;e+=2)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2];else d=r.subarray(c>>2,c+8*b>>2);I.uniform2iv(J(a),d)},jb:(a,b,c,d)=>{I.uniform3f(J(a),b,c,d)},ib:(a,b,c)=>{if(96>=b)for(var d=K[3*b-1],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);I.uniform3fv(J(a),d)},hb:(a,b,c,d)=>{I.uniform3i(J(a),b,c,
d)},gb:(a,b,c)=>{if(96>=b)for(var d=sb[3*b-1],e=0;e<3*b;e+=3)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2];else d=r.subarray(c>>2,c+12*b>>2);I.uniform3iv(J(a),d)},fb:(a,b,c,d,e)=>{I.uniform4f(J(a),b,c,d,e)},eb:(a,b,c)=>{if(72>=b){var d=K[4*b-1],e=v;c>>=2;for(var g=0;g<4*b;g+=4){var k=c+g;d[g]=e[k];d[g+1]=e[k+1];d[g+2]=e[k+2];d[g+3]=e[k+3]}}else d=v.subarray(c>>2,c+16*b>>2);I.uniform4fv(J(a),d)},cb:(a,b,c,d,e)=>{I.uniform4i(J(a),b,c,d,e)},bb:(a,b,c)=>{if(72>=b)for(var d=sb[4*b-1],
e=0;e<4*b;e+=4)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2],d[e+3]=r[c+(4*e+12)>>2];else d=r.subarray(c>>2,c+16*b>>2);I.uniform4iv(J(a),d)},ab:(a,b,c,d)=>{if(72>=b)for(var e=K[4*b-1],g=0;g<4*b;g+=4)e[g]=v[d+4*g>>2],e[g+1]=v[d+(4*g+4)>>2],e[g+2]=v[d+(4*g+8)>>2],e[g+3]=v[d+(4*g+12)>>2];else e=v.subarray(d>>2,d+16*b>>2);I.uniformMatrix2fv(J(a),!!c,e)},$a:(a,b,c,d)=>{if(32>=b)for(var e=K[9*b-1],g=0;g<9*b;g+=9)e[g]=v[d+4*g>>2],e[g+1]=v[d+(4*g+4)>>2],e[g+2]=v[d+(4*g+8)>>2],e[g+3]=v[d+
(4*g+12)>>2],e[g+4]=v[d+(4*g+16)>>2],e[g+5]=v[d+(4*g+20)>>2],e[g+6]=v[d+(4*g+24)>>2],e[g+7]=v[d+(4*g+28)>>2],e[g+8]=v[d+(4*g+32)>>2];else e=v.subarray(d>>2,d+36*b>>2);I.uniformMatrix3fv(J(a),!!c,e)},_a:(a,b,c,d)=>{if(18>=b){var e=K[16*b-1],g=v;d>>=2;for(var k=0;k<16*b;k+=16){var n=d+k;e[k]=g[n];e[k+1]=g[n+1];e[k+2]=g[n+2];e[k+3]=g[n+3];e[k+4]=g[n+4];e[k+5]=g[n+5];e[k+6]=g[n+6];e[k+7]=g[n+7];e[k+8]=g[n+8];e[k+9]=g[n+9];e[k+10]=g[n+10];e[k+11]=g[n+11];e[k+12]=g[n+12];e[k+13]=g[n+13];e[k+14]=g[n+14];
e[k+15]=g[n+15]}}else e=v.subarray(d>>2,d+64*b>>2);I.uniformMatrix4fv(J(a),!!c,e)},Za:a=>{a=C[a];I.useProgram(a);I.rd=a},Ya:a=>{I.validateProgram(C[a])},Xa:function(a,b){I.vertexAttrib1f(a,b)},Wa:(a,b)=>{I.vertexAttrib1f(a,v[b>>2])},Va:function(a,b,c){I.vertexAttrib2f(a,b,c)},Ta:(a,b)=>{I.vertexAttrib2f(a,v[b>>2],v[b+4>>2])},Sa:function(a,b,c,d){I.vertexAttrib3f(a,b,c,d)},Ra:(a,b)=>{I.vertexAttrib3f(a,v[b>>2],v[b+4>>2],v[b+8>>2])},Qa:function(a,b,c,d,e){I.vertexAttrib4f(a,b,c,d,e)},Pa:(a,b)=>{I.vertexAttrib4f(a,
v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},la:(a,b)=>{I.vertexAttribDivisor(a,b)},Oa:(a,b,c,d,e,g)=>{I.vertexAttribPointer(a,b,c,!!d,e,g)},Na:function(a,b,c,d){I.viewport(a,b,c,d)},Ma:(a,b,c)=>q.copyWithin(a,b,b+c),La:()=>{fa("OOM")},Fa:a=>{eval(a?z(q,a):"")},X:(a,b,c)=>{a=Na(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ha:(a,b,c)=>{a=R(a);ac(a,b,c)},Ia:(a,b,c,d)=>dc(a,b,c,d),c:vb,f:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var k=u[b>>2],n=u[b+4>>2];b+=8;for(var t=0;t<n;t++){var A=q[k+t],Y=ec[a];0===
A||10===A?((1===a?ea:l)(z(Y,0)),Y.length=0):Y.push(A)}e+=n}u[d>>2]=e;return 0},Ac:(a,b,c,d)=>{var e;for(e=0;e<U.length&&null!==U[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)g=0;else{d?Ob():Yb(a,b);for(e=0;e<U.length&&null==U[e];e++);d=0<S[139265];e==U.length&&(d?f.Kc=Lb(f.canvas,!0,!0,{antialias:1<S[135181],depth:0<S[135173],stencil:0<S[135174],alpha:0<S[135172]}):Jb());!f.Kc&&d?g=0:(a=new fc(g,a,b,c),g-1==U.length?U.push(a):U[g-1]=a,T=
a,g=a.id)}return g},Ga:a=>{a:{if(a=0>=a||!U?null:U[a-1]){a.md&&R(a.md)(a.id);U[a.id-1]=null;T.id==a.id&&(T=null);for(a=0;a<U.length;a++)if(null!==U[a]){a=void 0;break a}f.Kc=void 0}a=void 0}return a},a:(a,b,c)=>{la[b>>3]=P;la[c>>3]=Q},pc:()=>1,g:()=>Zb()/1E3-hc,ec:()=>0,M:()=>{if(U)return 1;hc=Zb()/1E3;S=ic;U=[];T=null;gc=devicePixelRatio;window.addEventListener("gamepadconnected",oc,!0);window.addEventListener("gamepaddisconnected",pc,!0);window.addEventListener("keydown",qc,!0);window.addEventListener("keypress",
lc,!0);window.addEventListener("keyup",rc,!0);window.addEventListener("blur",sc,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});gc=devicePixelRatio;T&&T.nd&&R(T.nd)(T.id,gc,gc)})();f.canvas.addEventListener("touchmove",tc,!0);f.canvas.addEventListener("touchstart",xc,!0);f.canvas.addEventListener("touchcancel",V,!0);f.canvas.addEventListener("touchend",V,!0);f.canvas.addEventListener("mousemove",tc,!0);f.canvas.addEventListener("mousedown",
xc,!0);f.canvas.addEventListener("mouseup",V,!0);f.canvas.addEventListener("wheel",yc,!0);f.canvas.addEventListener("mousewheel",yc,!0);f.canvas.addEventListener("mouseenter",uc,!0);f.canvas.addEventListener("mouseleave",vc,!0);f.canvas.addEventListener("drop",Cc,!0);f.canvas.addEventListener("dragover",Dc,!0);Xb.push((b,c)=>{if(T){var d=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(T.gd=T.x,T.hd=T.y,T.fd=T.width,T.ed=T.height,T.x=T.y=0,T.width=
screen.width,T.height=screen.height,T.Zc=!0):1==T.Zc?(T.x=T.gd,T.y=T.hd,T.width=T.fd,T.height=T.ed,T.Zc=!1):T.width!=b||T.height!=c?(T.width=b,T.height=c):d=!1;d&&(Yb(T.width,T.height,!0),T&&T.Vc&&R(T.Vc)(T.id,T.width,T.height),T&&T.cd&&R(T.cd)(T.id,T.width,T.height))}});return 1},Ua:()=>{},d:(a,b,c)=>{if(a=0>=a||!U?null:U[a-1])switch(b){case 208897:switch(c){case 212993:a.dd[b]=c;f.canvas.removeEventListener("click",Ec,!0);f.canvas.exitPointerLock();break;case 212994:l("glfwSetInputMode called with GLFW_CURSOR_HIDDEN value not implemented");
break;case 212995:a.dd[b]=c;f.canvas.addEventListener("click",Ec,!0);f.canvas.requestPointerLock();break;default:l(`glfwSetInputMode called with unknown value parameter value: ${c}`)}break;case 208898:l("glfwSetInputMode called with GLFW_STICKY_KEYS mode not implemented");break;case 208899:l("glfwSetInputMode called with GLFW_STICKY_MOUSE_BUTTONS mode not implemented");break;case 208900:l("glfwSetInputMode called with GLFW_LOCK_KEY_MODS mode not implemented");break;case 3342341:l("glfwSetInputMode called with GLFW_RAW_MOUSE_MOTION mode not implemented");
break;default:l(`glfwSetInputMode called with unknown mode parameter value: ${b}`)}},zb:(a,b)=>{if(a=0>=a||!U?null:U[a-1]){var c=a.Pc;a.Pc=b;b=c}else b=null;return b},ob:(a,b)=>{if(a=0>=a||!U?null:U[a-1]){var c=a.Tc;a.Tc=b;b=c}else b=null;return b},db:(a,b)=>{if(a=0>=a||!U?null:U[a-1]){var c=a.Uc;a.Uc=b;b=c}else b=null;return b},Vb:(a,b,c)=>{if(a=0>=a||!U?null:U[a-1])a.x=b,a.y=c},Kb:(a,b)=>{if(a=0>=a||!U?null:U[a-1]){var c=a.Vc;a.Vc=b;b=c}else b=null;return b},Bc:(a,b)=>{if(a=0>=a||!U?null:U[a-1])a.title=
b,T.id==a.id&&(document.title=b?z(q,b):"")},qa:()=>{},Ka:a=>{a=Math.abs(a);0==a?$b(0,0):$b(1,a)},e:()=>{window.removeEventListener("gamepadconnected",oc,!0);window.removeEventListener("gamepaddisconnected",pc,!0);window.removeEventListener("keydown",qc,!0);window.removeEventListener("keypress",lc,!0);window.removeEventListener("keyup",rc,!0);window.removeEventListener("blur",sc,!0);f.canvas.removeEventListener("touchmove",tc,!0);f.canvas.removeEventListener("touchstart",xc,!0);f.canvas.removeEventListener("touchcancel",
V,!0);f.canvas.removeEventListener("touchend",V,!0);f.canvas.removeEventListener("mousemove",tc,!0);f.canvas.removeEventListener("mousedown",xc,!0);f.canvas.removeEventListener("mouseup",V,!0);f.canvas.removeEventListener("wheel",yc,!0);f.canvas.removeEventListener("mousewheel",yc,!0);f.canvas.removeEventListener("mouseenter",uc,!0);f.canvas.removeEventListener("mouseleave",vc,!0);f.canvas.removeEventListener("drop",Cc,!0);f.canvas.removeEventListener("dragover",Dc,!0);f.canvas.width=f.canvas.height=
1;T=U=null},b:(a,b)=>{S[a]=b}},Z=function(){function a(c){Z=c.exports;ha=Z.Cc;c=ha.buffer;f.HEAP8=ja=new Int8Array(c);f.HEAP16=new Int16Array(c);f.HEAPU8=q=new Uint8Array(c);f.HEAPU16=ka=new Uint16Array(c);f.HEAP32=r=new Int32Array(c);f.HEAPU32=u=new Uint32Array(c);f.HEAPF32=v=new Float32Array(c);f.HEAPF64=la=new Float64Array(c);cc=Z.Fc;na.unshift(Z.Dc);w--;f.monitorRunDependencies&&f.monitorRunDependencies(w);0==w&&(null!==sa&&(clearInterval(sa),sa=null),ta&&(c=ta,ta=null,c()));return Z}var b={a:Hc};
w++;f.monitorRunDependencies&&f.monitorRunDependencies(w);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return l(`Module.instantiateWasm callback failed with error: ${c}`),!1}za(b,function(c){a(c.instance)});return{}}(),Ic=f._main=(a,b)=>(Ic=f._main=Z.Ec)(a,b),lb=a=>(lb=Z.Gc)(a),Bc=a=>(Bc=Z.Hc)(a),Jc=a=>(Jc=Z.Ic)(a),Kc;ta=function Lc(){Kc||Mc();Kc||(ta=Lc)};
function Nc(a=[]){var b=Ic;a.unshift(ca);var c=a.length,d=Jc(4*(c+1)),e=d;a.forEach(k=>{var n=u,t=e>>2,A=kb(k)+1,Y=Jc(A);B(k,Y,A);n[t]=Y;e+=4});u[e>>2]=0;try{var g=b(c,d);vb(g,!0)}catch(k){tb(k)}}
function Mc(){var a=ba;function b(){if(!Kc&&(Kc=!0,f.calledRun=!0,!p)){Ba(na);Ba(oa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Oc&&Nc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();qa.unshift(c)}Ba(qa)}}if(!(0<w)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ra();Ba(ma);0<w||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},
1)):b())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Oc=!0;f.noInitialRun&&(Oc=!1);Mc();
