
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",da=(a,b)=>{throw b;},h="";"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src);h=0!==h.indexOf("blob:")?h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var ea=f.print||console.log.bind(console),l=f.printErr||console.warn.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);
f.quit&&(da=f.quit);var fa;f.wasmBinary&&(fa=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&m("no native wasm support detected");var ha,p=!1,ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function r(a,b){if(a){var c=t,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&ia)a=ia.decode(c.subarray(a,b));else{for(d="";a<b;){var e=c[a++];if(e&128){var g=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}a=d}}else a="";return a}
function u(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var n=a.charCodeAt(++g);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ja(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var w,t,ka,x,y,z,la,ma,na=[],oa=[],pa=[],qa=[],ra=[];function sa(){var a=f.preRun.shift();na.unshift(a)}var A=0,ua=null,va=null;function m(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";l(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function wa(){return B.startsWith("data:application/octet-stream;base64,")}var B;B="index.wasm";
if(!wa()){var xa=B;B=f.locateFile?f.locateFile(xa,h):h+xa}function ya(){var a=B;try{if(a==B&&fa)return new Uint8Array(fa);throw"both async and sync fetching of the wasm failed";}catch(b){m(b)}}function za(){return fa||"function"!=typeof fetch?Promise.resolve().then(function(){return ya()}):fetch(B,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+B+"'";return a.arrayBuffer()}).catch(function(){return ya()})}
function Aa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ba(a){for(;0<a.length;)a.shift()(f)}var Ca=0;function Da(){for(var a=C.length-1;0<=a;--a)Ea(a);C=[];Fa=[]}var Fa=[];function Ga(){if(Ca&&Ha.ud)for(var a=0;a<Fa.length;++a){var b=Fa[a];Fa.splice(a,1);--a;b.Hd.apply(null,b.wd)}}var C=[];function Ea(a){var b=C[a];b.target.removeEventListener(b.Jc,b.md,b.gd);C.splice(a,1)}
function Ia(a){function b(d){++Ca;Ha=a;Ga();a.nd(d);Ga();--Ca}if(a.jd)a.md=b,a.target.addEventListener(a.Jc,b,a.gd),C.push(a),Ja||(qa.push(Da),Ja=!0);else for(var c=0;c<C.length;++c)C[c].target==a.target&&C[c].Jc==a.Jc&&Ea(c--)}var Ja,Ha,Ka,La=[0,document,window];function Ma(a){a=2<a?r(a):a;return La[a]||document.querySelector(a)}
function Na(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,k){b.drawElementsInstancedANGLE(c,d,e,g,k)})}
function Oa(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Pa(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Qa=1,Ra=[],E=[],Sa=[],F=[],G=[],H=[],Ta=[],Ua=[],I=[],Va={},Wa=4;
function J(a){Xa||(Xa=a)}function Ya(a){for(var b=Qa++,c=a.length;c<b;c++)a[c]=null;return b}function Za(a,b){a.Uc||(a.Uc=a.getContext,a.getContext=function(d,e){e=a.Uc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?$a(c,b):0}function $a(a,b){var c=Ya(Ua),d={Cd:c,attributes:b,version:b.qd,Qc:a};a.canvas&&(a.canvas.td=d);Ua[c]=d;("undefined"==typeof b.ld||b.ld)&&ab(d);return c}
function ab(a){a||(a=bb);if(!a.pd){a.pd=!0;var b=a.Qc;Na(b);Oa(b);Pa(b);b.Fc=b.getExtension("EXT_disjoint_timer_query");b.Fd=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var cb={},Xa,bb,eb=[];function fb(a,b,c,d){for(var e=0;e<a;e++){var g=K[c](),k=g&&Ya(d);g?(g.name=k,d[k]=g):J(1282);x[b+4*e>>2]=k}}
function gb(a,b,c,d,e,g,k,n){b=E[b];if(a=K[a](b,c))d=n&&u(a.name,t,n,d),e&&(x[e>>2]=d),g&&(x[g>>2]=a.size),k&&(x[k>>2]=a.type)}function hb(a,b){y[a>>2]=b;y[a+4>>2]=(b-y[a>>2])/4294967296}
function ib(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&J(1280);return;case 36345:d=0;break;case 34466:var e=K.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":J(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:J(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:w[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){J(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:J(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:hb(b,
d);break;case 0:x[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:w[b>>0]=d?1:0}}else J(1281)}function jb(a){var b=ja(a)+1,c=L(b);u(a,t,c,b);return c}function kb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function lb(a){var b=a.Hc,c=a.fd,d;if(!b)for(a.Hc=b={},a.ed={},d=0;d<K.getProgramParameter(a,35718);++d){var e=K.getActiveUniform(a,d);var g=e.name;e=e.size;var k=kb(g);k=0<k?g.slice(0,k):g;var n=a.Tc;a.Tc+=e;c[k]=[e,n];for(g=0;g<e;++g)b[n]=g,a.ed[n++]=k}}
function M(a){var b=K.kd;if(b){var c=b.Hc[a];"number"==typeof c&&(b.Hc[a]=c=K.getUniformLocation(b,b.ed[a]+(0<c?"["+c+"]":"")));return c}J(1282)}function mb(a,b,c,d){if(c)if(a=E[a],lb(a),a=K.getUniform(a,M(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else J(1281)}
function nb(a,b,c,d){if(c)if(a=K.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else J(1281)}
function ob(a,b,c,d,e){a-=5120;a=1==a?t:4==a?x:6==a?z:5==a||28922==a?y:ka;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),k=Wa;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+k-1&-k)>>g)}var N=[],pb=[];function qb(a){a instanceof Aa||"unwind"==a||da(1,a)}function rb(a){if(!p)try{a()}catch(b){qb(b)}}function sb(a){setTimeout(function(){rb(a)},1E4)}function tb(a){ub||(ub={});ub[a]||(ub[a]=1,l(a))}
var ub,vb=!1,O=null,P=0,wb=null,xb=0,yb=0,zb=0,R=0,Ab=[],Bb={},Cb,Db,Eb,Fb=!1,Gb=!1,Hb=[];
function Ib(){function a(){Gb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!Jb){Jb=!0;try{Kb=!0}catch(c){Kb=!1,l("warning: no blob constructor, cannot create blobs with mimetypes")}Lb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Kb?null:l("warning: no BlobBuilder");Mb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;f.Zc||"undefined"!=typeof Mb||(l("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.Zc=!0);f.preloadPlugins.push({canHandle:function(c){return!f.Zc&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var k=null;if(Kb)try{k=new Blob([c],{type:Nb(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:Nb(d)}))}catch(v){tb("Blob constructor present but fails: "+
v+"; falling back to blob builder")}k||(k=new Lb,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var n=Mb.createObjectURL(k),q=new Image;q.onload=()=>{q.complete||m("Image "+d+" could not be decoded");var v=document.createElement("canvas");v.width=q.width;v.height=q.height;v.getContext("2d").drawImage(q,0,0);Mb.revokeObjectURL(n);e&&e(c)};q.onerror=()=>{ea("Image "+n+" could not be decoded");g&&g()};q.src=n}});f.preloadPlugins.push({canHandle:function(c){return!f.Gd&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,g){function k(){q||(q=!0,e&&e(c))}function n(){q||(q=!0,new Audio,g&&g())}var q=!1;if(Kb){try{var v=new Blob([c],{type:Nb(d)})}catch(Q){return n()}v=Mb.createObjectURL(v);var D=new Audio;D.addEventListener("canplaythrough",()=>k(D),!1);D.onerror=function(){if(!q){l("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var Q="",ta=0,Y=0,db=0;db<c.length;db++)for(ta=ta<<8|c[db],Y+=8;6<=Y;){var Ic=ta>>Y-6&63;Y-=6;Q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[Ic]}2==
Y?(Q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(ta&3)<<4],Q+="=="):4==Y&&(Q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(ta&15)<<2],Q+="=");D.src="data:audio/x-"+d.substr(-3)+";base64,"+Q;k(D)}};D.src=v;sb(function(){k(D)})}else return n()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!Gb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Ob(a,b,c,d){if(b&&f.Gc&&a==f.canvas)return f.Gc;var e;if(b){var g={antialias:!1,alpha:!1,qd:1};if(d)for(var k in d)g[k]=d[k];if("undefined"!=typeof cb&&(e=Za(a,g)))var n=Ua[e].Qc}else n=a.getContext("2d");if(!n)return null;c&&(b||"undefined"==typeof K||m("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Gc=n,b&&(bb=Ua[e],f.Gc=K=bb&&bb.Qc),f.Id=b,Hb.forEach(function(q){q()}),Ib());return n}var Pb=!1,Qb=void 0,S=void 0;
function Rb(a,b){function c(){Fb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Sb,Qb&&d.requestPointerLock(),Fb=!0,S?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]|8388608),Tb(f.canvas),Ub()):Tb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),S?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]&-8388609),
Tb(f.canvas),Ub()):Tb(d));if(f.onFullScreen)f.onFullScreen(Fb);if(f.onFullscreen)f.onFullscreen(Fb)}Qb=a;S=b;"undefined"==typeof Qb&&(Qb=!0);"undefined"==typeof S&&(S=!1);var d=f.canvas;Pb||(Pb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}function Sb(){if(!Fb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Vb=0;
function Wb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Vb)Vb=b+1E3/60;else for(;b+2>=Vb;)Vb+=1E3/60;setTimeout(a,Math.max(Vb-b,0))}}function Nb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Xb=0,Yb=0,Zb=0,$b=0;
function ac(a){if(Gb)"mousemove"!=a.type&&"mozMovementX"in a?Zb=$b=0:(Zb=a.movementX||a.mozMovementX||a.webkitMovementX||0,$b=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Xb=SDL.Dd+Zb,Yb=SDL.Ed+$b):(Xb+=Zb,Yb+=$b);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,Zb=e-Xb,$b=a-Yb,Xb=e,Yb=a)}}var bc=[];function Ub(){var a=f.canvas;bc.forEach(function(b){b(a.width,a.height)})}function cc(a,b,c){Tb(f.canvas,a,b);c||Ub()}
function Tb(a,b,c){b&&c?(a.sd=b,a.od=c):(b=a.sd,c=a.od);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}S?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Jb,Kb,Lb,Mb;
function dc(a,b){yb=a;zb=b;if(wb)if(vb||(vb=!0),0==a)O=function(){var d=Math.max(0,Db+b-ec())|0;setTimeout(Eb,d)};else if(1==a)O=function(){Wb(Eb)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}O=function(){setImmediate(Eb)}}}var ec;ec=()=>performance.now();
function fc(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);p=!0}da(a,new Aa(a))}
function gc(a,b,c,d,e){!wb||m("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");wb=a;xb=d;var g=P;vb=!1;Eb=function(){if(!p)if(0<Ab.length){var k=Date.now(),n=Ab.shift();n.Bd(n.vd);if(Cb){var q=Cb,v=0==q%1?q-1:Math.floor(q);Cb=n.zd?v:(8*q+(v+.5))/9}ea('main loop blocker "'+n.name+'" took '+(Date.now()-k)+" ms");f.setStatus&&(k=f.statusMessage||"Please wait...",
n=Cb,q=Bb.Ad,n?n<q?f.setStatus(k+" ("+(q-n)+"/"+q+")"):f.setStatus(k):f.setStatus(""));g<P||setTimeout(Eb,0)}else g<P||(R=R+1|0,1==yb&&1<zb&&0!=R%zb?O():(0==yb&&(Db=ec()),p||f.preMainLoop&&!1===f.preMainLoop()||(rb(a),f.postMainLoop&&f.postMainLoop()),g<P||("object"==typeof SDL&&SDL.audio&&SDL.audio.rd&&SDL.audio.rd(),O())))};e||(b&&0<b?dc(0,1E3/b):dc(1,1),O());if(c)throw"unwind";}var hc=[];function T(a){var b=hc[a];b||(a>=hc.length&&(hc.length=a+1),hc[a]=b=ma.get(a));return b}
function ic(a,b,c,d){Ka||(Ka=L(36));a=Ma(a);Ia({target:a,Jc:"resize",jd:d,nd:function(e){e=e||event;if(e.target==a){var g=document.body;if(g){var k=Ka;x[k>>2]=e.detail;x[k+4>>2]=g.clientWidth;x[k+8>>2]=g.clientHeight;x[k+12>>2]=innerWidth;x[k+16>>2]=innerHeight;x[k+20>>2]=outerWidth;x[k+24>>2]=outerHeight;x[k+28>>2]=pageXOffset;x[k+32>>2]=pageYOffset;T(d)(10,k,b)&&e.preventDefault()}}},gd:c})}
function jc(a,b,c,d){this.id=a;this.y=this.x=0;this.Sc=!1;this.dd=this.cd=0;this.width=b;this.height=c;this.bd=b;this.ad=c;this.title=d;this.attributes=U;this.buttons=0;this.keys=[];this.Rc=[];this.Vc=this.Kc=this.Xc=this.$c=this.Ic=this.Wc=this.Oc=this.Yc=this.hd=this.Pc=this.title=null}function kc(a){return 0>=a||!V?null:V[a-1]}
var W=null,V=null,lc=null,U=null,mc={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function nc(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function oc(){var a=W,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function pc(a){W&&W.Vc&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||T(W.Vc)(W.id,a))}function qc(a,b){if(W){var c=nc(a);if(-1!=c){var d=b&&W.keys[c];W.keys[c]=b;W.Rc[a]=b;W.Kc&&(d&&(b=2),T(W.Kc)(W.id,c,a,b,oc()))}}}
function rc(){sc()}function tc(){sc()}function uc(a){qc(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function vc(a){qc(a.keyCode,0)}function wc(){if(W)for(var a=0;a<W.Rc.length;++a)W.Rc[a]&&qc(a,0)}function xc(a){W&&(ac(a),a.target==f.canvas&&W.Wc&&T(W.Wc)(W.id,Xb,Yb))}function yc(a){W&&a.target==f.canvas&&W.Ic&&T(W.Ic)(W.id,1)}function zc(a){W&&a.target==f.canvas&&W.Ic&&T(W.Ic)(W.id,0)}
function Ac(a,b){if(W&&(ac(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){W.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else W.buttons&=~(1<<c);W.Oc&&T(W.Oc)(W.id,c,b,oc())}}function Bc(a){W&&Ac(a,1)}function Cc(a){W&&Ac(a,0)}
function Dc(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(W&&W.$c&&a.target==f.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;T(W.$c)(W.id,b,c);a.preventDefault()}}
var X={},Ec=[],Fc=null;
function sc(){if(R!==Fc||!R){Ec=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];Fc=R;for(var a=0;a<Ec.length;++a){var b=Ec[a];if(b){if(!X[a]){ea("glfw joystick connected:",a);var c=a,d=b.id,e=ja(d)+1,g=L(e);g&&u(d,w,g,e);X[c]={id:g,yd:b.buttons.length,xd:b.axes.length,buttons:L(b.buttons.length),axes:L(4*b.axes.length)}}c=X[a];for(d=0;d<b.buttons.length;++d)w[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)z[c.axes+4*d>>2]=
b.axes[d]}else X[a]&&(ea("glfw joystick disconnected",a),Gc(X[a].id),Gc(X[a].buttons),Gc(X[a].axes),delete X[a])}}}function Hc(a){if(W&&W.Xc&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1}function Jc(a){if(W&&W.Xc)return a.preventDefault(),!1}for(var K,Z=0;32>Z;++Z)eb.push(Array(Z));var Kc=new Float32Array(288);for(Z=0;288>Z;++Z)N[Z]=Kc.subarray(0,Z+1);var Lc=new Int32Array(288);for(Z=0;288>Z;++Z)pb[Z]=Lc.subarray(0,Z+1);
f.requestFullscreen=function(a,b){Rb(a,b)};f.requestAnimationFrame=function(a){Wb(a)};f.setCanvasSize=function(a,b,c){cc(a,b,c)};f.pauseMainLoop=function(){O=null;P++};f.resumeMainLoop=function(){P++;var a=yb,b=zb,c=wb;wb=null;gc(c,0,!1,xb,!0);dc(a,b);O()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return Ob(a,b,c,d)};
var Mc={U:function(a,b,c){a=Ma(a);if(!a)return-4;a=0>La.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};la[b>>3]=a.width;la[c>>3]=a.height;return 0},la:function(a){K.activeTexture(a)},ka:function(a,b){K.attachShader(E[a],H[b])},Da:function(a,b){K.Fc.beginQueryEXT(a,I[b])},ja:function(a,b,c){K.bindAttribLocation(E[a],b,r(c))},ia:function(a,b){K.bindBuffer(a,Ra[b])},ha:function(a,b){K.bindFramebuffer(a,Sa[b])},ga:function(a,b){K.bindRenderbuffer(a,F[b])},fa:function(a,b){K.bindTexture(a,G[b])},
ua:function(a){K.bindVertexArray(Ta[a])},ea:function(a,b,c,d){K.blendColor(a,b,c,d)},ca:function(a){K.blendEquation(a)},ba:function(a,b){K.blendEquationSeparate(a,b)},aa:function(a,b){K.blendFunc(a,b)},$:function(a,b,c,d){K.blendFuncSeparate(a,b,c,d)},_:function(a,b,c,d){K.bufferData(a,c?t.subarray(c,c+b):b,d)},Z:function(a,b,c,d){K.bufferSubData(a,b,t.subarray(d,d+c))},Y:function(a){return K.checkFramebufferStatus(a)},X:function(a){K.clear(a)},W:function(a,b,c,d){K.clearColor(a,b,c,d)},V:function(a){K.clearDepth(a)},
T:function(a){K.clearStencil(a)},S:function(a,b,c,d){K.colorMask(!!a,!!b,!!c,!!d)},R:function(a){K.compileShader(H[a])},Q:function(a,b,c,d,e,g,k,n){K.compressedTexImage2D(a,b,c,d,e,g,n?t.subarray(n,n+k):null)},P:function(a,b,c,d,e,g,k,n,q){K.compressedTexSubImage2D(a,b,c,d,e,g,k,q?t.subarray(q,q+n):null)},O:function(a,b,c,d,e,g,k,n){K.copyTexImage2D(a,b,c,d,e,g,k,n)},N:function(a,b,c,d,e,g,k,n){K.copyTexSubImage2D(a,b,c,d,e,g,k,n)},M:function(){var a=Ya(E),b=K.createProgram();b.name=a;b.Nc=b.Lc=b.Mc=
0;b.Tc=1;E[a]=b;return a},L:function(a){var b=Ya(H);H[b]=K.createShader(a);return b},K:function(a){K.cullFace(a)},J:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Ra[d];e&&(K.deleteBuffer(e),e.name=0,Ra[d]=null)}},I:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Sa[d];e&&(K.deleteFramebuffer(e),e.name=0,Sa[d]=null)}},H:function(a){if(a){var b=E[a];b?(K.deleteProgram(b),b.name=0,E[a]=null):J(1281)}},Fa:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=I[d];e&&(K.Fc.deleteQueryEXT(e),
I[d]=null)}},G:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=F[d];e&&(K.deleteRenderbuffer(e),e.name=0,F[d]=null)}},F:function(a){if(a){var b=H[a];b?(K.deleteShader(b),H[a]=null):J(1281)}},E:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=G[d];e&&(K.deleteTexture(e),e.name=0,G[d]=null)}},ta:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];K.deleteVertexArray(Ta[d]);Ta[d]=null}},D:function(a){K.depthFunc(a)},C:function(a){K.depthMask(!!a)},B:function(a,b){K.depthRange(a,b)},A:function(a,
b){K.detachShader(E[a],H[b])},y:function(a){K.disable(a)},x:function(a){K.disableVertexAttribArray(a)},w:function(a,b,c){K.drawArrays(a,b,c)},pa:function(a,b,c,d){K.drawArraysInstanced(a,b,c,d)},qa:function(a,b){for(var c=eb[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];K.drawBuffers(c)},v:function(a,b,c,d){K.drawElements(a,b,c,d)},na:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,d,e)},u:function(a){K.enable(a)},t:function(a){K.enableVertexAttribArray(a)},Ca:function(a){K.Fc.endQueryEXT(a)},s:function(){K.finish()},
r:function(){K.flush()},q:function(a,b,c,d){K.framebufferRenderbuffer(a,b,c,F[d])},p:function(a,b,c,d,e){K.framebufferTexture2D(a,b,c,G[d],e)},n:function(a){K.frontFace(a)},m:function(a,b){fb(a,b,"createBuffer",Ra)},k:function(a,b){fb(a,b,"createFramebuffer",Sa)},Ga:function(a,b){for(var c=0;c<a;c++){var d=K.Fc.createQueryEXT();if(!d){for(J(1282);c<a;)x[b+4*c++>>2]=0;break}var e=Ya(I);d.name=e;I[e]=d;x[b+4*c>>2]=e}},j:function(a,b){fb(a,b,"createRenderbuffer",F)},i:function(a,b){fb(a,b,"createTexture",
G)},sa:function(a,b){fb(a,b,"createVertexArray",Ta)},l:function(a){K.generateMipmap(a)},h:function(a,b,c,d,e,g,k){gb("getActiveAttrib",a,b,c,d,e,g,k)},g:function(a,b,c,d,e,g,k){gb("getActiveUniform",a,b,c,d,e,g,k)},f:function(a,b,c,d){a=K.getAttachedShaders(E[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=H.indexOf(a[b])},e:function(a,b){return K.getAttribLocation(E[a],r(b))},vc:function(a,b){ib(a,b,4)},uc:function(a,b,c){c?x[c>>2]=K.getBufferParameter(a,b):J(1281)},tc:function(){var a=
K.getError()||Xa;Xa=0;return a},sc:function(a,b){ib(a,b,2)},rc:function(a,b,c,d){a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},qc:function(a,b){ib(a,b,0)},oc:function(a,b,c,d){a=K.getProgramInfoLog(E[a]);null===a&&(a="(unknown error)");b=0<b&&d?u(a,t,d,b):0;c&&(x[c>>2]=b)},pc:function(a,b,c){if(c)if(a>=Qa)J(1281);else if(a=E[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==
b){if(!a.Nc)for(b=0;b<K.getProgramParameter(a,35718);++b)a.Nc=Math.max(a.Nc,K.getActiveUniform(a,b).name.length+1);x[c>>2]=a.Nc}else if(35722==b){if(!a.Lc)for(b=0;b<K.getProgramParameter(a,35721);++b)a.Lc=Math.max(a.Lc,K.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.Lc}else if(35381==b){if(!a.Mc)for(b=0;b<K.getProgramParameter(a,35382);++b)a.Mc=Math.max(a.Mc,K.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.Mc}else x[c>>2]=K.getProgramParameter(a,b);else J(1281)},wa:function(a,b,c){if(c){a=K.Fc.getQueryObjectEXT(I[a],
b);var d;"boolean"==typeof a?d=a?1:0:d=a;hb(c,d)}else J(1281)},ya:function(a,b,c){if(c){a=K.Fc.getQueryObjectEXT(I[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else J(1281)},va:function(a,b,c){if(c){a=K.Fc.getQueryObjectEXT(I[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;hb(c,d)}else J(1281)},xa:function(a,b,c){if(c){a=K.Fc.getQueryObjectEXT(I[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else J(1281)},Aa:function(a,b,c){c?x[c>>2]=K.Fc.getQueryEXT(a,b):J(1281)},nc:function(a,b,c){c?
x[c>>2]=K.getRenderbufferParameter(a,b):J(1281)},kc:function(a,b,c,d){a=K.getShaderInfoLog(H[a]);null===a&&(a="(unknown error)");b=0<b&&d?u(a,t,d,b):0;c&&(x[c>>2]=b)},jc:function(a,b,c,d){a=K.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},ic:function(a,b,c,d){if(a=K.getShaderSource(H[a]))b=0<b&&d?u(a,t,d,b):0,c&&(x[c>>2]=b)},mc:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(H[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(H[a]),
x[c>>2]=a?a.length+1:0):x[c>>2]=K.getShaderParameter(H[a],b):J(1281)},hc:function(a){var b=Va[a];if(!b){switch(a){case 7939:b=K.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=jb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=K.getParameter(a))||J(1280);b=b&&jb(b);break;case 7938:b=jb("OpenGL ES 2.0 ("+K.getParameter(7938)+")");break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&
(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=jb(b);break;default:J(1280)}Va[a]=b}return b},gc:function(a,b,c){c?z[c>>2]=K.getTexParameter(a,b):J(1281)},fc:function(a,b,c){c?x[c>>2]=K.getTexParameter(a,b):J(1281)},cc:function(a,b){b=r(b);if(a=E[a]){lb(a);var c=a.Hc,d=0,e=b,g=kb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.fd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else J(1281);return-1},ec:function(a,b,c){mb(a,b,c,2)},dc:function(a,b,c){mb(a,b,
c,0)},_b:function(a,b,c){c?x[c>>2]=K.getVertexAttribOffset(a,b):J(1281)},bc:function(a,b,c){nb(a,b,c,2)},$b:function(a,b,c){nb(a,b,c,5)},Zb:function(a,b){K.hint(a,b)},Yb:function(a){return(a=Ra[a])?K.isBuffer(a):0},Xb:function(a){return K.isEnabled(a)},Wb:function(a){return(a=Sa[a])?K.isFramebuffer(a):0},Vb:function(a){return(a=E[a])?K.isProgram(a):0},Ea:function(a){return(a=I[a])?K.Fc.isQueryEXT(a):0},Ub:function(a){return(a=F[a])?K.isRenderbuffer(a):0},Tb:function(a){return(a=H[a])?K.isShader(a):
0},Sb:function(a){return(a=G[a])?K.isTexture(a):0},ra:function(a){return(a=Ta[a])?K.isVertexArray(a):0},Qb:function(a){K.lineWidth(a)},Pb:function(a){a=E[a];K.linkProgram(a);a.Hc=0;a.fd={}},Ob:function(a,b){3317==a&&(Wa=b);K.pixelStorei(a,b)},Nb:function(a,b){K.polygonOffset(a,b)},Ba:function(a,b){K.Fc.queryCounterEXT(I[a],b)},Mb:function(a,b,c,d,e,g,k){(k=ob(g,e,c,d,k))?K.readPixels(a,b,c,d,e,g,k):J(1280)},Lb:function(){},Kb:function(a,b,c,d){K.renderbufferStorage(a,b,c,d)},Jb:function(a,b){K.sampleCoverage(a,
!!b)},Ib:function(a,b,c,d){K.scissor(a,b,c,d)},Hb:function(){J(1280)},Fb:function(a,b,c,d){for(var e="",g=0;g<b;++g){var k=d?x[d+4*g>>2]:-1;e+=r(x[c+4*g>>2],0>k?void 0:k)}K.shaderSource(H[a],e)},Eb:function(a,b,c){K.stencilFunc(a,b,c)},Db:function(a,b,c,d){K.stencilFuncSeparate(a,b,c,d)},Cb:function(a){K.stencilMask(a)},Bb:function(a,b){K.stencilMaskSeparate(a,b)},Ab:function(a,b,c){K.stencilOp(a,b,c)},zb:function(a,b,c,d){K.stencilOpSeparate(a,b,c,d)},yb:function(a,b,c,d,e,g,k,n,q){K.texImage2D(a,
b,c,d,e,g,k,n,q?ob(n,k,d,e,q):null)},xb:function(a,b,c){K.texParameterf(a,b,c)},wb:function(a,b,c){K.texParameterf(a,b,z[c>>2])},ub:function(a,b,c){K.texParameteri(a,b,c)},tb:function(a,b,c){K.texParameteri(a,b,x[c>>2])},sb:function(a,b,c,d,e,g,k,n,q){var v=null;q&&(v=ob(n,k,e,g,q));K.texSubImage2D(a,b,c,d,e,g,k,n,v)},rb:function(a,b){K.uniform1f(M(a),b)},qb:function(a,b,c){if(288>=b)for(var d=N[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);K.uniform1fv(M(a),d)},pb:function(a,
b){K.uniform1i(M(a),b)},ob:function(a,b,c){if(288>=b)for(var d=pb[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);K.uniform1iv(M(a),d)},nb:function(a,b,c){K.uniform2f(M(a),b,c)},mb:function(a,b,c){if(144>=b)for(var d=N[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);K.uniform2fv(M(a),d)},lb:function(a,b,c){K.uniform2i(M(a),b,c)},jb:function(a,b,c){if(144>=b)for(var d=pb[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];
else d=x.subarray(c>>2,c+8*b>>2);K.uniform2iv(M(a),d)},ib:function(a,b,c,d){K.uniform3f(M(a),b,c,d)},hb:function(a,b,c){if(96>=b)for(var d=N[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);K.uniform3fv(M(a),d)},gb:function(a,b,c,d){K.uniform3i(M(a),b,c,d)},fb:function(a,b,c){if(96>=b)for(var d=pb[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);K.uniform3iv(M(a),
d)},eb:function(a,b,c,d,e){K.uniform4f(M(a),b,c,d,e)},db:function(a,b,c){if(72>=b){var d=N[4*b-1],e=z;c>>=2;for(var g=0;g<4*b;g+=4){var k=c+g;d[g]=e[k];d[g+1]=e[k+1];d[g+2]=e[k+2];d[g+3]=e[k+3]}}else d=z.subarray(c>>2,c+16*b>>2);K.uniform4fv(M(a),d)},cb:function(a,b,c,d,e){K.uniform4i(M(a),b,c,d,e)},bb:function(a,b,c){if(72>=b)for(var d=pb[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);K.uniform4iv(M(a),
d)},ab:function(a,b,c,d){if(72>=b)for(var e=N[4*b-1],g=0;g<4*b;g+=4)e[g]=z[d+4*g>>2],e[g+1]=z[d+(4*g+4)>>2],e[g+2]=z[d+(4*g+8)>>2],e[g+3]=z[d+(4*g+12)>>2];else e=z.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(M(a),!!c,e)},_a:function(a,b,c,d){if(32>=b)for(var e=N[9*b-1],g=0;g<9*b;g+=9)e[g]=z[d+4*g>>2],e[g+1]=z[d+(4*g+4)>>2],e[g+2]=z[d+(4*g+8)>>2],e[g+3]=z[d+(4*g+12)>>2],e[g+4]=z[d+(4*g+16)>>2],e[g+5]=z[d+(4*g+20)>>2],e[g+6]=z[d+(4*g+24)>>2],e[g+7]=z[d+(4*g+28)>>2],e[g+8]=z[d+(4*g+32)>>2];else e=z.subarray(d>>
2,d+36*b>>2);K.uniformMatrix3fv(M(a),!!c,e)},Za:function(a,b,c,d){if(18>=b){var e=N[16*b-1],g=z;d>>=2;for(var k=0;k<16*b;k+=16){var n=d+k;e[k]=g[n];e[k+1]=g[n+1];e[k+2]=g[n+2];e[k+3]=g[n+3];e[k+4]=g[n+4];e[k+5]=g[n+5];e[k+6]=g[n+6];e[k+7]=g[n+7];e[k+8]=g[n+8];e[k+9]=g[n+9];e[k+10]=g[n+10];e[k+11]=g[n+11];e[k+12]=g[n+12];e[k+13]=g[n+13];e[k+14]=g[n+14];e[k+15]=g[n+15]}}else e=z.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(M(a),!!c,e)},Ya:function(a){a=E[a];K.useProgram(a);K.kd=a},Xa:function(a){K.validateProgram(E[a])},
Wa:function(a,b){K.vertexAttrib1f(a,b)},Va:function(a,b){K.vertexAttrib1f(a,z[b>>2])},Ua:function(a,b,c){K.vertexAttrib2f(a,b,c)},Ta:function(a,b){K.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},Sa:function(a,b,c,d){K.vertexAttrib3f(a,b,c,d)},Ra:function(a,b){K.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},Pa:function(a,b,c,d,e){K.vertexAttrib4f(a,b,c,d,e)},Oa:function(a,b){K.vertexAttrib4f(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},ma:function(a,b){K.vertexAttribDivisor(a,b)},Na:function(a,b,c,d,e,g){K.vertexAttribPointer(a,
b,c,!!d,e,g)},Ma:function(a,b,c,d){K.viewport(a,b,c,d)},La:function(a,b,c){t.copyWithin(a,b,b+c)},Ka:function(){m("OOM")},Ha:function(a){eval(r(a))},oa:function(a,b,c){a=Ma(a);if(!a)return-4;a.width=b;a.height=c;return 0},Qa:function(a,b,c){a=T(a);gc(a,b,c)},$a:function(a,b,c,d){ic(a,b,c,d);return 0},b:fc,z:function(a,b,c,d){var e;for(e=0;e<V.length&&null!==V[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)g=0;else{d?Rb():cc(a,b);for(e=0;e<
V.length&&null==V[e];e++);d=0<U[139265];e==V.length&&(d?f.Gc=Ob(f.canvas,!0,!0,{antialias:1<U[135181],depth:0<U[135173],stencil:0<U[135174],alpha:0<U[135172]}):Ib());!f.Gc&&d?g=0:(a=new jc(g,a,b,c),g-1==V.length?V.push(a):V[g-1]=a,W=a,g=a.id)}return g},Ja:function(a){a:{if(a=kc(a)){a.hd&&T(a.hd)(a.id);V[a.id-1]=null;W.id==a.id&&(W=null);for(a=0;a<V.length;a++)if(null!==V[a]){a=void 0;break a}f.Gc=void 0}a=void 0}return a},Ia:function(a,b,c){la[b>>3]=Xb;la[c>>3]=Yb},o:function(){return 1},d:function(){return ec()/
1E3-lc},wc:function(){return 0},da:function(){if(V)return 1;lc=ec()/1E3;U=mc;V=[];W=null;window.addEventListener("gamepadconnected",rc,!0);window.addEventListener("gamepaddisconnected",tc,!0);window.addEventListener("keydown",uc,!0);window.addEventListener("keypress",pc,!0);window.addEventListener("keyup",vc,!0);window.addEventListener("blur",wc,!0);f.canvas.addEventListener("touchmove",xc,!0);f.canvas.addEventListener("touchstart",Bc,!0);f.canvas.addEventListener("touchcancel",Cc,!0);f.canvas.addEventListener("touchend",
Cc,!0);f.canvas.addEventListener("mousemove",xc,!0);f.canvas.addEventListener("mousedown",Bc,!0);f.canvas.addEventListener("mouseup",Cc,!0);f.canvas.addEventListener("wheel",Dc,!0);f.canvas.addEventListener("mousewheel",Dc,!0);f.canvas.addEventListener("mouseenter",yc,!0);f.canvas.addEventListener("mouseleave",zc,!0);f.canvas.addEventListener("drop",Hc,!0);f.canvas.addEventListener("dragover",Jc,!0);bc.push((a,b)=>{if(W){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?
(W.cd=W.x,W.dd=W.y,W.bd=W.width,W.ad=W.height,W.x=W.y=0,W.width=screen.width,W.height=screen.height,W.Sc=!0):1==W.Sc?(W.x=W.cd,W.y=W.dd,W.width=W.bd,W.height=W.ad,W.Sc=!1):W.width!=a||W.height!=b?(W.width=a,W.height=b):c=!1;c&&(cc(W.width,W.height,!0),W&&W.Pc&&T(W.Pc)(W.id,W.width,W.height),W&&W.Yc&&T(W.Yc)(W.id,W.width,W.height))}});return 1},vb:function(){},Rb:function(a,b){if(a=kc(a)){var c=a.Kc;a.Kc=b;b=c}else b=null;return b},Gb:function(a,b){if(a=kc(a)){var c=a.Oc;a.Oc=b;b=c}else b=null;return b},
lc:function(a,b,c){if(a=kc(a))a.x=b,a.y=c},ac:function(a,b){if(a=kc(a)){var c=a.Pc;a.Pc=b;b=c}else b=null;return b},xc:function(a,b){if(a=kc(a))a.title=r(b),W.id==a.id&&(document.title=a.title)},za:function(){},kb:function(a){a=Math.abs(a);0==a?dc(0,0):dc(1,a)},c:function(){window.removeEventListener("gamepadconnected",rc,!0);window.removeEventListener("gamepaddisconnected",tc,!0);window.removeEventListener("keydown",uc,!0);window.removeEventListener("keypress",pc,!0);window.removeEventListener("keyup",
vc,!0);window.removeEventListener("blur",wc,!0);f.canvas.removeEventListener("touchmove",xc,!0);f.canvas.removeEventListener("touchstart",Bc,!0);f.canvas.removeEventListener("touchcancel",Cc,!0);f.canvas.removeEventListener("touchend",Cc,!0);f.canvas.removeEventListener("mousemove",xc,!0);f.canvas.removeEventListener("mousedown",Bc,!0);f.canvas.removeEventListener("mouseup",Cc,!0);f.canvas.removeEventListener("wheel",Dc,!0);f.canvas.removeEventListener("mousewheel",Dc,!0);f.canvas.removeEventListener("mouseenter",
yc,!0);f.canvas.removeEventListener("mouseleave",zc,!0);f.canvas.removeEventListener("drop",Hc,!0);f.canvas.removeEventListener("dragover",Jc,!0);f.canvas.width=f.canvas.height=1;W=V=null},a:function(a,b){U[a]=b}};
(function(){function a(e){f.asm=e.exports;ha=f.asm.yc;e=ha.buffer;f.HEAP8=w=new Int8Array(e);f.HEAP16=new Int16Array(e);f.HEAP32=x=new Int32Array(e);f.HEAPU8=t=new Uint8Array(e);f.HEAPU16=ka=new Uint16Array(e);f.HEAPU32=y=new Uint32Array(e);f.HEAPF32=z=new Float32Array(e);f.HEAPF64=la=new Float64Array(e);ma=f.asm.Bc;oa.unshift(f.asm.zc);A--;f.monitorRunDependencies&&f.monitorRunDependencies(A);0==A&&(null!==ua&&(clearInterval(ua),ua=null),va&&(e=va,va=null,e()))}function b(e){a(e.instance)}function c(e){return za().then(function(g){return WebAssembly.instantiate(g,
d)}).then(function(g){return g}).then(e,function(g){l("failed to asynchronously prepare wasm: "+g);m(g)})}var d={a:Mc};A++;f.monitorRunDependencies&&f.monitorRunDependencies(A);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return fa||"function"!=typeof WebAssembly.instantiateStreaming||wa()||"function"!=typeof fetch?c(b):fetch(B,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(g){l("wasm streaming compile failed: "+g);l("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.zc).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Ac).apply(null,arguments)};
var L=f._malloc=function(){return(L=f._malloc=f.asm.Cc).apply(null,arguments)},Gc=f._free=function(){return(Gc=f._free=f.asm.Dc).apply(null,arguments)},Nc=f.stackAlloc=function(){return(Nc=f.stackAlloc=f.asm.Ec).apply(null,arguments)},Oc;va=function Pc(){Oc||Qc();Oc||(va=Pc)};function Rc(a){var b=f._main;a=a||[];a.unshift(ca);var c=a.length,d=Nc(4*(c+1)),e=d>>2;a.forEach(k=>{var n=x,q=e++,v=ja(k)+1,D=Nc(v);u(k,w,D,v);n[q]=D});x[e]=0;try{var g=b(c,d);fc(g,!0)}catch(k){qb(k)}}
function Qc(){function a(){if(!Oc&&(Oc=!0,f.calledRun=!0,!p)){Ba(oa);Ba(pa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Sc&&Rc(b);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();ra.unshift(c)}Ba(ra)}}var b=b||ba;if(!(0<A)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)sa();Ba(na);0<A||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);
a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Sc=!0;f.noInitialRun&&(Sc=!1);Qc();
